- name: configurig apache2
  hosts: all
  tasks:
    - name: installing apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: coping content
      copy:
        content: welcome
        dest: /var/www/html/index.html  
    - name: restarting apache
      service:
        name: apache2
        state: restarted
    - name: pausing
      pause:
        seconds: 60
    - name: checking url in service 1
      uri:
        url: http://172.31.32.125
        status_code: 200
    - name: checking url in service 
      uri:
        url: http://172.31.39.241
        status_code: 200
        
 

